# Generated by Django 5.2.4 on 2025-08-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creation', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[("Не обов'язково", "Не обов'язково"), ('Бажано', 'Бажано'), ("Обов'язково", "Обов'язково")], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Треба робити', 'Треба робити'), ('В процесі', 'В процесі'), ('Зроблено', 'Зроблено')], default='todo', max_length=20),
        ),
    ]
